[package]
name = "cargo-sdl-apk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="cargo-sdl-apk"
path="src/main.rs"

[dependencies]
toml = "0.7.3"
fs_extra = "1.3.0"
symlink = "0.1.0"
